### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by techmonsterwang** [RICE-EIC/ShiftAddNet#2]
Hi, Author.
I have noticed that the experiments shown in the paper say that "Specifically, with full-precision
floating-point (FP32) ShiftAddNet even surpasses both the multiplication-based ConvNet and the
AdderNet". However, I wonder if the data format is FP-32, how can we use shift? Can float point data use shift operation? If so, how?

**Comment by ranery** [comment]
Thanks for your interest in our work.

Regarding the FP32 format in the shift layer, we meant the corresponding usage in the backpropagation and update of the weight parameters, which are signs and shift bits following the DeepShift (PS).

The FP32 cannot be shifted so that the forwarding pass in the shift layer is done with a fixed format, same with the DeepShift.

Hope the above description can solve your question!

**Comment by ranery** [comment]
I will close this issue, feel free to re-open it if you have any other questions.

**Comment by brisker** [comment]
@ranery
hi, I am a little confused about, why there is no imagenet results in your paper?
